[build]
  command = "rustup default stable && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y && export PATH=$PATH:$HOME/.cargo/bin && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  RUST_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
